/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShellCanvasRouteImport } from './routes/_shell.canvas'
import { Route as ShellCommandRouteImport } from './routes/_shell.command'
import { Route as ShellCompetitorsRouteImport } from './routes/_shell.competitors'
import { Route as ShellCopilotRouteImport } from './routes/_shell.copilot'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellFinanceRouteImport } from './routes/_shell.finance'
import { Route as ShellHelpRouteImport } from './routes/_shell.help'
import { Route as ShellInterviewRouteImport } from './routes/_shell.interview'
import { Route as ShellInvestorRouteImport } from './routes/_shell.investor'
import { Route as ShellJourneyRouteImport } from './routes/_shell.journey'
import { Route as ShellOverviewRouteImport } from './routes/_shell.overview'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellRiskRouteImport } from './routes/_shell.risk'
import { Route as ShellRoadmapRouteImport } from './routes/_shell.roadmap'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellStrategyRouteImport } from './routes/_shell.strategy'
import { Route as ShellValidationRouteImport } from './routes/_shell.validation'
import { Route as ShellStartupsIndexRouteImport } from './routes/_shell.startups.index'
import { Route as ShellStartupsNewRouteImport } from './routes/_shell.startups.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCanvasRoute = ShellCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCommandRoute = ShellCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCompetitorsRoute = ShellCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCopilotRoute = ShellCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFinanceRoute = ShellFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHelpRoute = ShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInterviewRoute = ShellInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInvestorRoute = ShellInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => ShellRoute,
} as any)
const ShellJourneyRoute = ShellJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOverviewRoute = ShellOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRiskRoute = ShellRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRoadmapRoute = ShellRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStrategyRoute = ShellStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => ShellRoute,
} as any)
const ShellValidationRoute = ShellValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStartupsIndexRoute = ShellStartupsIndexRouteImport.update({
  id: '/startups/',
  path: '/startups/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStartupsNewRoute = ShellStartupsNewRouteImport.update({
  id: '/startups/new',
  path: '/startups/new',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/canvas': typeof ShellCanvasRoute
  '/command': typeof ShellCommandRoute
  '/competitors': typeof ShellCompetitorsRoute
  '/copilot': typeof ShellCopilotRoute
  '/dashboard': typeof ShellDashboardRoute
  '/finance': typeof ShellFinanceRoute
  '/help': typeof ShellHelpRoute
  '/interview': typeof ShellInterviewRoute
  '/investor': typeof ShellInvestorRoute
  '/journey': typeof ShellJourneyRoute
  '/overview': typeof ShellOverviewRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/risk': typeof ShellRiskRoute
  '/roadmap': typeof ShellRoadmapRoute
  '/settings': typeof ShellSettingsRoute
  '/strategy': typeof ShellStrategyRoute
  '/validation': typeof ShellValidationRoute
  '/startups/new': typeof ShellStartupsNewRoute
  '/startups/': typeof ShellStartupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/canvas': typeof ShellCanvasRoute
  '/command': typeof ShellCommandRoute
  '/competitors': typeof ShellCompetitorsRoute
  '/copilot': typeof ShellCopilotRoute
  '/dashboard': typeof ShellDashboardRoute
  '/finance': typeof ShellFinanceRoute
  '/help': typeof ShellHelpRoute
  '/interview': typeof ShellInterviewRoute
  '/investor': typeof ShellInvestorRoute
  '/journey': typeof ShellJourneyRoute
  '/overview': typeof ShellOverviewRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/risk': typeof ShellRiskRoute
  '/roadmap': typeof ShellRoadmapRoute
  '/settings': typeof ShellSettingsRoute
  '/strategy': typeof ShellStrategyRoute
  '/validation': typeof ShellValidationRoute
  '/startups/new': typeof ShellStartupsNewRoute
  '/startups': typeof ShellStartupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/_shell/canvas': typeof ShellCanvasRoute
  '/_shell/command': typeof ShellCommandRoute
  '/_shell/competitors': typeof ShellCompetitorsRoute
  '/_shell/copilot': typeof ShellCopilotRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/finance': typeof ShellFinanceRoute
  '/_shell/help': typeof ShellHelpRoute
  '/_shell/interview': typeof ShellInterviewRoute
  '/_shell/investor': typeof ShellInvestorRoute
  '/_shell/journey': typeof ShellJourneyRoute
  '/_shell/overview': typeof ShellOverviewRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/risk': typeof ShellRiskRoute
  '/_shell/roadmap': typeof ShellRoadmapRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/strategy': typeof ShellStrategyRoute
  '/_shell/validation': typeof ShellValidationRoute
  '/_shell/startups/new': typeof ShellStartupsNewRoute
  '/_shell/startups/': typeof ShellStartupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/canvas'
    | '/command'
    | '/competitors'
    | '/copilot'
    | '/dashboard'
    | '/finance'
    | '/help'
    | '/interview'
    | '/investor'
    | '/journey'
    | '/overview'
    | '/profile'
    | '/reports'
    | '/risk'
    | '/roadmap'
    | '/settings'
    | '/strategy'
    | '/validation'
    | '/startups/new'
    | '/startups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/canvas'
    | '/command'
    | '/competitors'
    | '/copilot'
    | '/dashboard'
    | '/finance'
    | '/help'
    | '/interview'
    | '/investor'
    | '/journey'
    | '/overview'
    | '/profile'
    | '/reports'
    | '/risk'
    | '/roadmap'
    | '/settings'
    | '/strategy'
    | '/validation'
    | '/startups/new'
    | '/startups'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/auth'
    | '/_shell/canvas'
    | '/_shell/command'
    | '/_shell/competitors'
    | '/_shell/copilot'
    | '/_shell/dashboard'
    | '/_shell/finance'
    | '/_shell/help'
    | '/_shell/interview'
    | '/_shell/investor'
    | '/_shell/journey'
    | '/_shell/overview'
    | '/_shell/profile'
    | '/_shell/reports'
    | '/_shell/risk'
    | '/_shell/roadmap'
    | '/_shell/settings'
    | '/_shell/strategy'
    | '/_shell/validation'
    | '/_shell/startups/new'
    | '/_shell/startups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/canvas': {
      id: '/_shell/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof ShellCanvasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/command': {
      id: '/_shell/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof ShellCommandRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/competitors': {
      id: '/_shell/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof ShellCompetitorsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/copilot': {
      id: '/_shell/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof ShellCopilotRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/finance': {
      id: '/_shell/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof ShellFinanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/help': {
      id: '/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ShellHelpRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/interview': {
      id: '/_shell/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof ShellInterviewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/investor': {
      id: '/_shell/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof ShellInvestorRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/journey': {
      id: '/_shell/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof ShellJourneyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/overview': {
      id: '/_shell/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof ShellOverviewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/risk': {
      id: '/_shell/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof ShellRiskRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/roadmap': {
      id: '/_shell/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof ShellRoadmapRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/strategy': {
      id: '/_shell/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof ShellStrategyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/validation': {
      id: '/_shell/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ShellValidationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/startups/': {
      id: '/_shell/startups/'
      path: '/startups'
      fullPath: '/startups/'
      preLoaderRoute: typeof ShellStartupsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/startups/new': {
      id: '/_shell/startups/new'
      path: '/startups/new'
      fullPath: '/startups/new'
      preLoaderRoute: typeof ShellStartupsNewRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCanvasRoute: typeof ShellCanvasRoute
  ShellCommandRoute: typeof ShellCommandRoute
  ShellCompetitorsRoute: typeof ShellCompetitorsRoute
  ShellCopilotRoute: typeof ShellCopilotRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFinanceRoute: typeof ShellFinanceRoute
  ShellHelpRoute: typeof ShellHelpRoute
  ShellInterviewRoute: typeof ShellInterviewRoute
  ShellInvestorRoute: typeof ShellInvestorRoute
  ShellJourneyRoute: typeof ShellJourneyRoute
  ShellOverviewRoute: typeof ShellOverviewRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellRiskRoute: typeof ShellRiskRoute
  ShellRoadmapRoute: typeof ShellRoadmapRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellStrategyRoute: typeof ShellStrategyRoute
  ShellValidationRoute: typeof ShellValidationRoute
  ShellStartupsNewRoute: typeof ShellStartupsNewRoute
  ShellStartupsIndexRoute: typeof ShellStartupsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCanvasRoute: ShellCanvasRoute,
  ShellCommandRoute: ShellCommandRoute,
  ShellCompetitorsRoute: ShellCompetitorsRoute,
  ShellCopilotRoute: ShellCopilotRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFinanceRoute: ShellFinanceRoute,
  ShellHelpRoute: ShellHelpRoute,
  ShellInterviewRoute: ShellInterviewRoute,
  ShellInvestorRoute: ShellInvestorRoute,
  ShellJourneyRoute: ShellJourneyRoute,
  ShellOverviewRoute: ShellOverviewRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellRiskRoute: ShellRiskRoute,
  ShellRoadmapRoute: ShellRoadmapRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellStrategyRoute: ShellStrategyRoute,
  ShellValidationRoute: ShellValidationRoute,
  ShellStartupsNewRoute: ShellStartupsNewRoute,
  ShellStartupsIndexRoute: ShellStartupsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
