import { createFileRoute } from "@tanstack/react-router";
import { Copy, Download } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";

import { AiBadge, PageHeader, SurfaceCard } from "@/components/common/ui-kit";
import { ModuleFrame } from "@/components/common/ai-module-panel";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { useWorkspace } from "@/lib/workspace-context";
import {
  aiModulesService,
  type AiMeta,
  type BusinessStrategyData,
} from "@/services/ai-modules-service";

export const Route = createFileRoute("/_shell/strategy")({
  head: () => ({
    meta: [
      { title: "Business Strategy — AI Business Strategy Copilot" },
      { name: "description", content: "Executive summary, positioning, business model, pricing, marketing, go-to-market and growth strategy generated by AI." },
      { property: "og:title", content: "Business Strategy — AI Business Strategy Copilot" },
      { property: "og:description", content: "A full business strategy document generated from your interview." },
    ],
  }),
  component: Strategy,
});

function Strategy() {
  const { activeStartup, activeId } = useWorkspace();
  const [data, setData] = useState<BusinessStrategyData | null>(null);
  const [meta, setMeta] = useState<AiMeta | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadLatest = useCallback(async () => {
    if (!activeId) return;
    setLoading(true);
    setError(null);
    try {
      const report = await aiModulesService.getLatestReport<BusinessStrategyData>("business_strategy");
      if (report) {
        setData(report.data);
        setMeta(report.ai_meta);
      } else {
        setData(null);
        setMeta(null);
      }
    } catch (err: any) {
      setError(err?.message || "Failed to load strategy report.");
    } finally {
      setLoading(false);
    }
  }, [activeId]);

  useEffect(() => {
    loadLatest();
  }, [loadLatest]);

  const generate = async () => {
    setGenerating(true);
    setError(null);
    try {
      const report = await aiModulesService.generateBusinessStrategy();
      setData(report.data);
      setMeta(report.ai_meta);
      toast.success(`Business strategy generated! v${report.ai_meta.report_version}`);
    } catch (err: any) {
      setError(err?.message || "AI generation failed. Please try again.");
      toast.error("Failed to generate strategy.");
    } finally {
      setGenerating(false);
    }
  };

  const copy = (text: string, label: string) => {
    void navigator.clipboard?.writeText(text);
    toast.success(`${label} copied to clipboard`);
  };

  const copyAll = () => {
    if (!data) return;
    const topText = [
      data.executive_summary && `Executive Summary\n${data.executive_summary}`,
      data.mission && `Mission\n${data.mission}`,
      data.vision && `Vision\n${data.vision}`,
    ]
      .filter(Boolean)
      .join("\n\n");
    const sections = (data.sections || []).map((s) => `${s.title}\n${s.body}`).join("\n\n");
    copy([topText, sections].filter(Boolean).join("\n\n"), "Full strategy");
  };

  // Top 3 highlighted sections
  const topSections = data
    ? [
        { title: "Executive Summary", body: data.executive_summary },
        { title: "Mission", body: data.mission },
        { title: "Vision", body: data.vision },
      ].filter((s) => s.body)
    : [];

  const remainingSections = data?.sections || [];
  const versionLabel = meta ? `Strategy v${meta.report_version}` : "";

  return (
    <>
      <PageHeader
        eyebrow={`${activeStartup.name}${versionLabel ? " · " + versionLabel : ""}`}
        title="Business Strategy"
        subtitle="AI-generated strategy document from your interview, validation scores and market data."
        actions={
          data ? (
            <>
              <Button variant="outline" onClick={() => toast.success("Strategy exported as PDF")}>
                <Download /> Export
              </Button>
              <Button variant="hero" onClick={copyAll}>
                <Copy /> Copy all
              </Button>
            </>
          ) : null
        }
      />

      <ModuleFrame
        loading={loading}
        generating={generating}
        error={error}
        hasData={!!data}
        meta={meta}
        emptyTitle="Generate Your Business Strategy"
        emptyDescription={`Let AI craft a complete strategy for ${activeStartup.name} — executive summary, GTM, revenue model, sales, growth, technology and KPIs.`}
        onGenerate={generate}
        onRegenerate={generate}
        loadingMessage="AI is building your complete business strategy…"
      >
        {data && (
          <>
            <div className="grid gap-4 md:grid-cols-3">
              {topSections.map((s) => (
                <SurfaceCard key={s.title}>
                  <AiBadge>AI generated</AiBadge>
                  <h2 className="mt-3 text-base font-semibold">{s.title}</h2>
                  <p className="mt-2 text-sm text-muted-foreground">{s.body}</p>
                  <Button variant="ghost" size="sm" className="mt-3 -ml-2" onClick={() => copy(s.body!, s.title)}>
                    <Copy /> Copy
                  </Button>
                </SurfaceCard>
              ))}
            </div>

            {data.target_market && (
              <SurfaceCard>
                <h2 className="text-base font-semibold">Target Market</h2>
                <p className="mt-2 text-sm text-muted-foreground">{data.target_market}</p>
              </SurfaceCard>
            )}

            {remainingSections.length > 0 && (
              <SurfaceCard hover={false} className="p-2 sm:p-4">
                <Accordion type="multiple" defaultValue={remainingSections[0] ? [remainingSections[0].title] : []}>
                  {remainingSections.map((s) => (
                    <AccordionItem key={s.title} value={s.title}>
                      <AccordionTrigger className="px-2 text-left text-base font-semibold hover:no-underline">
                        {s.title}
                      </AccordionTrigger>
                      <AccordionContent className="px-2">
                        <p className="text-sm leading-relaxed text-muted-foreground">{s.body}</p>
                        <Button variant="ghost" size="sm" className="mt-2 -ml-2" onClick={() => copy(s.body, s.title)}>
                          <Copy /> Copy section
                        </Button>
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </SurfaceCard>
            )}

            {data.kpis?.length > 0 && (
              <SurfaceCard>
                <h2 className="text-base font-semibold">Key Performance Indicators</h2>
                <ul className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
                  {data.kpis.map((kpi) => (
                    <li key={kpi} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm">
                      <span className="size-1.5 shrink-0 rounded-full bg-primary" />
                      {kpi}
                    </li>
                  ))}
                </ul>
              </SurfaceCard>
            )}
          </>
        )}
      </ModuleFrame>
    </>
  );
}
